generate:
	protoc --go_out=pkg/ --go_opt=paths=source_relative \
               --go-grpc_out=pkg/ --go-grpc_opt=paths=source_relative \
               --proto_path=api/ \
               api/users/users.proto api/groups/groups.proto